version: "3"

tasks:
  fmt:
    desc: "Run clang-format"
    cmds:
      - clang-format -i src/**/*.cpp src/**/*.hpp
  qdbus-gen:
    dir: src/dbus
    cmds:
      - qdbusxml2cpp-qt6 -a DisplayAdaptorGen DisplaySchema.xml
  setup:
    desc: "Run cmake configuration"
    cmds:
      - cmake -S . -B build -G Ninja
  build: cmake --build build
  build-watch: watchman-make -p '**/*.cpp' '**/*.h' --run "task cook"
  cook:
    cmds:
      - task setup
      - task build
  install: sudo ninja install -C build