version: "3"

tasks:
  fmt:
    desc: "Run clang-format"
    cmds:
      - clang-format -i src/**/*.cpp src/**/*.hpp
  qdbus-gen:
    desc: "Generate qdbus adaptors"
    dir: src/dbus
    cmds:
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/DisplayAdaptorGen schemas/DisplaySchema.Displays.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/BatchSystemAdaptorGen schemas/DisplaySchema.BatchSystem.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/OutputAdaptorGen schemas/DisplaySchema.Output.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/OutputModeAdaptorGen schemas/DisplaySchema.OutputMode.xml
  setup:
    desc: "Run cmake configuration"
    cmds:
      - cmake -S . -B build -G Ninja
  build:
    desc: "Run cmake build"
    cmds:
      - cmake --build build
  build-watch:
    desc: "Run cmake build on file change using watchman"
    cmds:
      - watchman-make -p '**/*.cpp' '**/*.h' --run "task cook"
  cook:
    desc: "Run cmake setup and build"
    cmds:
      - go-task setup
      - go-task build
  install:
    desc: "Run ninja install"
    cmds:
      - sudo ninja install -C build
  wldbg-build:
    desc: "Run wldbg (wayland-debug) against build"
    cmds:
      - wldbg -r ./build/src/org.buddiesofbudgie.BudgieDaemonV2 -g