/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was DisplaySchema.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DISPLAYADAPTORGEN_H
#define DISPLAYADAPTORGEN_H

#include <QtCore/qcontainerfwd.h>

#include <QtCore/QObject>
#include <QtDBus/QtDBus>

/*
 * Adaptor class for interface org.buddiesofbudgie.BudgieDaemonX.Displays
 */
class DisplaysAdaptor : public QDBusAbstractAdaptor {
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.buddiesofbudgie.BudgieDaemonX.Displays")
    Q_CLASSINFO(
        "D-Bus Introspection",
        ""
        "  <interface name=\"org.buddiesofbudgie.BudgieDaemonX.Displays\">\n"
        "    <method name=\"GetAvailableOutputs\">\n"
        "      <annotation value=\"QStringList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
        "      <arg direction=\"out\" type=\"as\" name=\"outputs\"/>\n"
        "    </method>\n"
        "    <method name=\"GetCurrentOutputDetails\">\n"
        "      <annotation value=\"QString\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
        "      <annotation value=\"QString\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.Out1\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.Out2\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.Out3\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.Out4\"/>\n"
        "      <annotation value=\"double\" name=\"org.qtproject.QtDBus.QtTypeName.Out5\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.Out6\"/>\n"
        "      <annotation value=\"bool\" name=\"org.qtproject.QtDBus.QtTypeName.Out7\"/>\n"
        "      <annotation value=\"bool\" name=\"org.qtproject.QtDBus.QtTypeName.Out8\"/>\n"
        "      <arg direction=\"in\" type=\"s\" name=\"serial\"/>\n"
        "      <arg direction=\"out\" type=\"s\" name=\"name\"/>\n"
        "      <arg direction=\"out\" type=\"i\" name=\"width\"/>\n"
        "      <arg direction=\"out\" type=\"i\" name=\"height\"/>\n"
        "      <arg direction=\"out\" type=\"i\" name=\"x\"/>\n"
        "      <arg direction=\"out\" type=\"i\" name=\"y\"/>\n"
        "      <arg direction=\"out\" type=\"d\" name=\"scale\"/>\n"
        "      <arg direction=\"out\" type=\"i\" name=\"refresh\"/>\n"
        "      <arg direction=\"out\" type=\"b\" name=\"preferred\"/>\n"
        "      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
        "    </method>\n"
        "    <method name=\"GetAvailableModes\">\n"
        "      <annotation value=\"QString\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
        "      <annotation value=\"QList&lt;QList&lt;int&gt;&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
        "      <arg direction=\"in\" type=\"s\" name=\"serial\"/>\n"
        "      <arg direction=\"out\" type=\"a(iii)\" name=\"modes\"/>\n"
        "    </method>\n"
        "    <method name=\"SetCurrentMode\">\n"
        "      <annotation value=\"QString\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
        "      <annotation value=\"double\" name=\"org.qtproject.QtDBus.QtTypeName.In3\"/>\n"
        "      <annotation value=\"bool\" name=\"org.qtproject.QtDBus.QtTypeName.In4\"/>\n"
        "      <arg direction=\"in\" type=\"s\" name=\"serial\"/>\n"
        "      <arg direction=\"in\" type=\"i\" name=\"width\"/>\n"
        "      <arg direction=\"in\" type=\"i\" name=\"height\"/>\n"
        "      <arg direction=\"in\" type=\"d\" name=\"refresh\"/>\n"
        "      <arg direction=\"in\" type=\"b\" name=\"preferred\"/>\n"
        "    </method>\n"
        "    <method name=\"SetOutputPosition\">\n"
        "      <annotation value=\"QString\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
        "      <annotation value=\"int\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
        "      <arg direction=\"in\" type=\"s\" name=\"serial\"/>\n"
        "      <arg direction=\"in\" type=\"i\" name=\"x\"/>\n"
        "      <arg direction=\"in\" type=\"i\" name=\"y\"/>\n"
        "    </method>\n"
        "    <method name=\"SetOutputEnabled\">\n"
        "      <annotation value=\"QString\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
        "      <annotation value=\"bool\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
        "      <arg direction=\"in\" type=\"s\" name=\"serial\"/>\n"
        "      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
        "    </method>\n"
        "  </interface>\n"
        "")
  public:
    DisplaysAdaptor(QObject* parent);
    ~DisplaysAdaptor() override;

  public:          // PROPERTIES
  public Q_SLOTS:  // METHODS
    QList<QList<int>> GetAvailableModes(const QString& serial);
    QStringList       GetAvailableOutputs();
    QString
         GetCurrentOutputDetails(const QString& serial, int& width, int& height, int& x, int& y, double& scale, int& refresh, bool& preferred, bool& enabled);
    void SetCurrentMode(const QString& serial, int width, int height, double refresh, bool preferred);
    void SetOutputEnabled(const QString& serial, bool enabled);
    void SetOutputPosition(const QString& serial, int x, int y);
  Q_SIGNALS:  // SIGNALS
};

#endif
