/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was DisplaySchema.Displays.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DisplayAdaptorGen.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DisplaysAdaptor
 */

DisplaysAdaptor::DisplaysAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DisplaysAdaptor::~DisplaysAdaptor()
{
    // destructor
}

QStringList DisplaysAdaptor::GetAvailableOutputs()
{
    // handle method call org.buddiesofbudgie.BudgieDaemonX.Displays.GetAvailableOutputs
    QStringList outputSerials{};
    QMetaObject::invokeMethod(parent(), "GetAvailableOutputs", Q_RETURN_ARG(QStringList, outputSerials));
    return outputSerials;
}

